[project]
name = "portfolio-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "st-gsheets-connection>=0.1.0",
    "streamlit>=1.50.0",
]
